---
output: 
  pdf_document:
    df_print: kable
    latex_engine: xelatex
    keep_tex: true
---
```{r setup, include=FALSE}
# options(kableExtra.auto_format = FALSE,
#         knitr.table.format = "latex"
#         )

knitr::opts_chunk$set(echo = FALSE, 
                      include = FALSE,
                      # dev = 'jpeg', 
                      fig.width = 8, 
                      fig.height = 6, 
                      message = FALSE,
                      warning = FALSE,
                      cache = FALSE
                      )
```

```{r}
#' load packages
library("tidyverse")
library("scales")
library("conflicted")
library("knitr")

# Resolve package function conflicts
conflict_prefer('filter', 'dplyr')
conflict_prefer('select', 'dplyr')
conflict_prefer('kable', 'knitr')
```

```{r}
#create a folder for storing the manuscript figures

if (!dir.exists("../figs_manuscript")) {
  dir.create("../figs_manuscript",
    showWarnings = TRUE
  )
}

#save figures in this folder
save_fig_here <- '../figs_manuscript'
```


```{r}
# Load the cleaned data 
long_data <- read_rds('../data/review_data_long_cleaned.rds')

#The cleaned data without citations
compact_data_init <- read_rds('../data/review_data_compact_cleaned.rds')
```

```{r}
# Load the data with citations
compact_data_with_citation_keys_init <- read_rds("../data/compact_data_with_citation_keys_cleaned.rds")

# Clean various variables
compact_data_with_citation_keys <- compact_data_with_citation_keys_init %>%
  mutate(vax_modelled = ifelse(str_detect(intervention_modelled, "vaccination"),
    "yes",
    "no"
  ), 
  intervention_type = case_when(
    vax_modelled == "no" & vax_modelled_with_non_vax == "no" ~ "no_vax", # Vaccination was not modelled
    vax_modelled == "yes" & vax_modelled_with_non_vax == "no" ~ "vax_combination_with_others", # when vax was modelled but not for comparison as a single intervention
    vax_modelled == "yes" & vax_modelled_with_non_vax == "yes" ~ "vax_single", # when vax was modelled as a single intervention
  ),
    publication_year = as.numeric(publication_year),
    author_in_country_studied = as.character(author_in_country_studied)
  ) %>%
  arrange(publication_year) %>%
  mutate(
    author_affiliation_type = str_replace_all(author_affiliation_type, " ", " + "),
    author_in_country_studied = if_else(author_in_country_studied == "NA", "not_applicable",
      author_in_country_studied
    ),
    year_aggreg = as.numeric(ifelse(publication_year < 2006, # An approach to aggregate the years before 2006 into one group because of the low number of papers
      2005,
      publication_year
    )),
    collab_type = as_factor(if_else(author_affiliation_type == "academic_institutions",
      "purely_academic",
      "mixed"
    ))
  )
```

```{r}
# Data dictionaries

# parametrization description dictionary
parametrization_str_replacements <- c(
  "values_from_literature" = "literature",
  "values_from_guess_and_expert_opion" = "expert_opinion",
  "values_fitted_to_ts" = "fitted",
  " " = " and " # replace space with 'and' to make it more readable
)

# validation description dictionary
validation_str_replacements <- c(
  "compared_with_data" = "data",
  "compared_with_other_model_output" = "another_model",
  "model_not_validated" = "none",
  " " = "_and_"
)

# Clean the parametrization and validation variables with dictionary
compact_data_with_citation_keys <- compact_data_with_citation_keys %>%
  mutate(parametrization = str_replace_all(
    parametrization,
    parametrization_str_replacements
  )) %>%
  mutate(validation = str_replace_all(
    validation,
    validation_str_replacements
  )) %>%
  mutate(model_structure = str_replace(model_structure, 
                                       "deterministic stochastic", 
                                       "both"
                                       )
         )
```

```{r}
# Rearrange the columns
compact_data_with_citation_keys <- compact_data_with_citation_keys %>%
  relocate(c(title, bibtexkey), .before = publication_year) %>%
  relocate(publication_year, .before = bibtexkey) %>%
  relocate(c(x0_reviewer, category, author:language),
    .after = collab_type
  )
```


```{r}
# Remove unneeded columns and rearrange the remainder
 final_citation_table <- compact_data_with_citation_keys %>% 
     relocate(c('doi', 'year', 'bibtexkey'), .after = title) %>% 
     select(-c(year_aggreg, x0_reviewer, category, 
               number, pages, journal, publisher, 
               volume, language, month, publication_type, 
               modelling_timing, intervention_type, collab_type,
               author, paper_doi, year, 
               doi, bibtexkey
               )
            ) %>% 
     arrange(desc(publication_year))
```

```{r}
# Make a neat table of papers from columns 1(title)-5
final_citation_table %>% 
    select(1:5) %>% 
    kable()

# booktabs = TRUE,
#       longtable = FALSE#,
#       # caption = 'Extracted data per paper: publication_year, author_affiliation_type, country_studied, author_in_country_studied.'
#          ) %>%
#     kable_styling(latex_options = c('striped',
#                                     'scale_down',
#                                     'hold_position',
#                                     'repeat_header'
#                                     )
#                   ) %>%
#     column_spec(column = c(1, 3), width = "5cm") #%>%
    # landscape()
```


<!--  ```{r} -->
<!-- # Make a neat table of papers from columns 1 (title), and 6-10  -->
<!-- final_citation_table %>% -->
<!--   select(c(1, 6:10)) %>% -->
<!--   kable( -->
<!--     booktabs = TRUE, -->
<!--     longtable = FALSE, -->
<!--     caption = "Extracted data per paper: disease, objectives, individual_representation, space_representation, model_structure." -->
<!--   ) %>% -->
<!--   kable_styling(latex_options = c("striped",  -->
<!--                                   "scale_down",  -->
<!--                                   "hold_position",  -->
<!--                                   "repeat_header" -->
<!--                                   ) -->
<!--                 ) %>% -->
<!--   column_spec(column = c(1), width = "5cm") %>% -->
<!--   landscape() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Make a neat table of papers from columns 1 (title) and 11-15  -->
<!-- final_citation_table %>% -->
<!--   select(1, 11:15) %>% -->
<!--   kable( -->
<!--     longtable = FALSE, -->
<!--     caption = "Extracted data per paper: parametrization, validation, outbreak_type, intervention_modelled, vax_modelled_with_non_vax." -->
<!--   ) %>% -->
<!--   kable_styling(latex_options = c("striped",  -->
<!--                                   "scale_down",  -->
<!--                                   "hold_position",  -->
<!--                                   "repeat_header" -->
<!--                                   ) -->
<!--                 ) %>% -->
<!--   column_spec(column = c(1, 2, 5), width = "4cm") %>% -->
<!--   landscape() -->
<!-- ``` -->

<!--  ```{r} -->
<!-- # Make a neat table of papers from columns 1 (title) and 16-22 -->
<!-- final_citation_table %>% -->
<!--   select(1, 16:22) %>% -->
<!--   kable( -->
<!--     booktabs = TRUE, -->
<!--     longtable = FALSE, -->
<!--     caption = "Extracted data per paper: is_vax_effective, outcome_measured, sensitivity_analysis, data_used, data_available, simulation_code_available, vax_modelled." -->
<!--   ) %>% -->
<!--   kable_styling(latex_options = c("striped", -->
<!--                                   "scale_down",  -->
<!--                                   "hold_position",  -->
<!--                                   "repeat_header" -->
<!--                                   ) -->
<!--                 ) %>% -->
<!--   column_spec(column = c(1, 3), width = "5cm") %>% -->
<!--   landscape() -->
<!-- ``` -->
